### ISSUE TITLE
Host project on Heroku

### ISSUE THREAD

**Issue by ameliejyc** [FAC-11/week5-ASSKITTY#14]
!

**Comment by maxgerber** [comment]
There were a couple of issues here but it is now up and running.
I followed this tutorial which is banging and should go in the readme. [banging tutorial](https://drublic.de/blog/how-to-set-up-herokuapp/)
I first removed the require of env2 because we don't use it in heroku and it points to a file we've gitignored which broke the code.
I then changed the Procfile I'd created to actually take in the dynamic port number which is quite well documented online - ```web: node src/server.js -p $PORT```
I then changed the default of hostname from 'localhost' to '0.0.0.0'. This is what seemed to fully fix it! I don't think heroku has a hostname environment variable at all, and for some reason localhost fucked with its brain. That solution was completely buried in google search [buried solution to problems](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1071)
I should really go to bed. Sorry guys.
